services:
  - type: web
    name: backend
    env: node
    plan: free  # You can change this if you're using a different plan
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_API_KEY
        sync: false # Example environment variable (update or add more as needed)
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
